CREATE TABLE PERSONNEL
(
    SSN              CHAR(10)    NOT NULL
        CONSTRAINT PK_PERSONNEL PRIMARY KEY,
    FIRST_NAME       VARCHAR(32) NOT NULL,
    SECOND_NAME      VARCHAR(32),
    THIRD_NAME       VARCHAR(32) NOT NULL,
    ADDRESS          VARCHAR(64) NOT NULL,
    WORKING_HOURS    INT
        CONSTRAINT CHK_PERSONNEL_WH CHECK (WORKING_HOURS > 0),
    TELEPHONE_NUMBER CHAR(10)    NOT NULL
);

CREATE TABLE MEDICAL_AUXILIARIES
(
    SSN              CHAR(10)    NOT NULL
        CONSTRAINT PK_PERSONNEL PRIMARY KEY,
    FIRST_NAME       VARCHAR(32) NOT NULL,
    SECOND_NAME      VARCHAR(32),
    THIRD_NAME       VARCHAR(32) NOT NULL,
    ADDRESS          VARCHAR(64) NOT NULL,
    WORKING_HOURS    INT
        CONSTRAINT CHK_PERSONNEL_WH CHECK (WORKING_HOURS > 0),
    TELEPHONE_NUMBER CHAR(10)    NOT NULL
);

CREATE TABLE SUBJECT_ROOMS
(
    NUMBER INT         NOT NULL
        CONSTRAINT PK_SUBJECT_ROOMS PRIMARY KEY
        CONSTRAINT CHK_SUBJECT_ROOMS CHECK ( NUMBER >= 0 ),
    NAME   VARCHAR(16) NOT NULL
);

CREATE TABLE TEACHERS
(
    SSN              CHAR(10)    NOT NULL
        CONSTRAINT PK_TEACHERS PRIMARY KEY,
    FIRST_NAME       VARCHAR(32) NOT NULL,
    SECOND_NAME      VARCHAR(32),
    THIRD_NAME       VARCHAR(32) NOT NULL,
    ADDRESS          VARCHAR(64) NOT NULL,
    WORKING_HOURS    INT
        CONSTRAINT CHK_TEACHERS_WH CHECK (WORKING_HOURS > 0),
    TELEPHONE_NUMBER CHAR(10)    NOT NULL,
    HEADMASTER       CHAR(10)
        CONSTRAINT FK_TEACHERS_HEADMASTER REFERENCES TEACHERS (SSN),
    VICE_HEADMASTER  CHAR(10)
        CONSTRAINT FK_TEACHERS_VICE_HEADMASTER REFERENCES TEACHERS (SSN),
    HEAD_OF_ROOM     INT
        CONSTRAINT CHK_TEACHERS_ROOM CHECK ( HEAD_OF_ROOM >= 0 )
        CONSTRAINT FK_TEACHERS REFERENCES SUBJECT_ROOMS (NUMBER)
);

CREATE TABLE MAJORS
(
    NAME VARCHAR(16) NOT NULL
        CONSTRAINT PK_MAJORS PRIMARY KEY
);

CREATE TABLE CLASSES
(
    NUMBER          INT         NOT NULL
        CONSTRAINT CHK_CLASSES_NUMBER CHECK ( NUMBER BETWEEN 8 AND 12 ),
    LETTER          CHAR(1)     NOT NULL
        CONSTRAINT CHK_CLASSES_LETTER CHECK ( LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    MAJOR           VARCHAR(16) NOT NULL
        CONSTRAINT FK_CLASSES_MAJORS REFERENCES MAJORS (NAME),
    LEADING_TEACHER CHAR(10)    NOT NULL
        CONSTRAINT FK_CLASSES_TEACHERS REFERENCES TEACHERS (SSN),
    CONSTRAINT PK_CLASSES PRIMARY KEY (NUMBER, LETTER)
);

CREATE TABLE GUARDIANS
(
    SSN              CHAR(10)    NOT NULL
        CONSTRAINT PK_GUARDIANS PRIMARY KEY,
    FIRST_NAME       VARCHAR(32) NOT NULL,
    SECOND_NAME      VARCHAR(32),
    THIRD_NAME       VARCHAR(32) NOT NULL,
    ADDRESS          VARCHAR(64) NOT NULL,
    TELEPHONE_NUMBER CHAR(10)    NOT NULL
);

CREATE TABLE STUDENTS
(
    NUMBER       INT         NOT NULL
        CONSTRAINT CHK_STUDENTS_NUMBER CHECK ( NUMBER BETWEEN 1 AND 32),
    FIRST_NAME   VARCHAR(32) NOT NULL,
    SECOND_NAME  VARCHAR(32),
    THIRD_NAME   VARCHAR(32) NOT NULL,
    CLASS_NUMBER INT         NOT NULL
        CONSTRAINT CHK_STUDENTS_CLASSES_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12),
    CLASS_LETTER CHAR(1)     NOT NULL
        CONSTRAINT CHK_STUDENTS_CLASSES_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    GUARDIAN     CHAR(10)    NOT NULL
        CONSTRAINT FK_STUDENTS_GUARDIAN REFERENCES GUARDIANS (SSN),
    CONSTRAINT PK_STUDENTS PRIMARY KEY (NUMBER, CLASS_NUMBER, CLASS_LETTER),
    CONSTRAINT FK_STUDENTS FOREIGN KEY (CLASS_NUMBER, CLASS_LETTER) REFERENCES CLASSES (NUMBER, LETTER)
);

CREATE TABLE MEDICAL_RECORDS
(
    MEDICAL_AUXILIARY CHAR(10) NOT NULL
        CONSTRAINT FK_MEDICAL_RECORDS_AUXILIARY REFERENCES MEDICAL_AUXILIARIES (SSN),
    CLASS_NUMBER      INT      NOT NULL
        CONSTRAINT CHK_MEDICAL_RECORDS_STUDENT_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12),
    CLASS_LETTER      CHAR(1)  NOT NULL
        CONSTRAINT CHK_MEDICAL_RECORDS_STUDENT_CLASS_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    STUDENT_NUMBER    INT      NOT NULL
        CONSTRAINT CHK_MEDICAL_RECORDS_STUDENTS_NUMBER CHECK ( STUDENT_NUMBER BETWEEN 1 AND 32),
    CONSTRAINT FK_MEDICAL_RECORDS_STUDENT FOREIGN KEY (CLASS_NUMBER, CLASS_LETTER, STUDENT_NUMBER)
        REFERENCES STUDENTS (CLASS_NUMBER, CLASS_LETTER, NUMBER),
    CONSTRAINT PK_MEDICAL_RECORDS PRIMARY KEY (MEDICAL_AUXILIARY, CLASS_NUMBER, CLASS_LETTER, STUDENT_NUMBER)
);

CREATE TABLE SUBJECTS
(
    NAME VARCHAR(16) NOT NULL
        CONSTRAINT PK_SUBJECTS PRIMARY KEY
);

CREATE TABLE SUBJECTS_IN_MAJORS
(
    MAJOR   VARCHAR(16) NOT NULL
        CONSTRAINT FK_SUBJECTS_SUBJECTS_IN_MAJORS_MAJOR REFERENCES MAJORS (NAME),
    SUBJECT VARCHAR(16) NOT NULL
        CONSTRAINT FK_SUBJECTS_SUBJECTS_IN_MAJORS_SUBJECT REFERENCES SUBJECTS (NAME),
    CONSTRAINT PK_SUBJECTS_IN_MAJORS PRIMARY KEY (MAJOR, SUBJECT)
);

CREATE TABLE TEACHES
(
    TEACHER CHAR(10)    NOT NULL
        CONSTRAINT FK_TEACHES_TEACHER REFERENCES TEACHERS (SSN),
    SUBJECT VARCHAR(16) NOT NULL
        CONSTRAINT FK_TEACHES_SUBJECT REFERENCES SUBJECTS (NAME),
    CONSTRAINT PK_TEACHES PRIMARY KEY (TEACHER, SUBJECT)
);

CREATE TABLE E_GRADEBOOKS
(
    ABSENCES_EXCUSED     DECIMAL(5, 2) DEFAULT 0 NOT NULL
        CONSTRAINT CHK_E_GRADEBOOKS_ABSENCES_EXCUSED CHECK ( ABSENCES_EXCUSED BETWEEN 0 AND 300),
    ABSENCES_NOT_EXCUSED DECIMAL(4, 2) DEFAULT 0 NOT NULL
        CONSTRAINT CHK_E_GRADEBOOKS_ABSENCES_NOT_EXCUSED CHECK ( ABSENCES_NOT_EXCUSED BETWEEN 0 AND 15),
    COMMENT              VARCHAR(1024),
    STUDENT_NUMBER       INT                     NOT NULL
        CONSTRAINT CHK_E_GRADEBOOKS_STUDENT_NUMBER CHECK ( STUDENT_NUMBER BETWEEN 1 AND 32),
    CLASS_NUMBER         INT                     NOT NULL
        CONSTRAINT CHK_E_GRADEBOOKS_CLASS_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12),
    CLASS_LETTER         CHAR(1)                 NOT NULL
        CONSTRAINT CHK_E_GRADEBOOKS_CLASS_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    CONSTRAINT FK_E_GRADEBOOKS FOREIGN KEY (CLASS_NUMBER, CLASS_LETTER, STUDENT_NUMBER)
        REFERENCES STUDENTS (CLASS_NUMBER, CLASS_LETTER, NUMBER),
    CONSTRAINT PK_E_GRADEBOOKS PRIMARY KEY (STUDENT_NUMBER, CLASS_NUMBER, CLASS_LETTER)
);

CREATE TABLE ACCESSES
(
    GUARDIAN     CHAR(10) NOT NULL
        CONSTRAINT FK_ACCESSES_GUARDIAN REFERENCES GUARDIANS (SSN),
    STUDENT      INT      NOT NULL
        CONSTRAINT CHK_ACCESSES_STUDENT CHECK ( STUDENT BETWEEN 1 AND 32),
    CLASS_NUMBER INT      NOT NULL
        CONSTRAINT CHK_ACCESSES_CLASS_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12),
    CLASS_LETTER CHAR(1)  NOT NULL
        CONSTRAINT CHK_ACCESSES_CLASS_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    CONSTRAINT FK_ACCESSES_E_GRADEBOOK FOREIGN KEY (STUDENT, CLASS_NUMBER, CLASS_LETTER)
        REFERENCES E_GRADEBOOKS (STUDENT_NUMBER, CLASS_NUMBER, CLASS_LETTER),
    CONSTRAINT PK_ACCESSES PRIMARY KEY (GUARDIAN, STUDENT, CLASS_NUMBER, CLASS_LETTER)
);

CREATE TABLE FILLS
(
    TEACHER      CHAR(10) NOT NULL
        CONSTRAINT FK_FILLS_TEACHER REFERENCES TEACHERS (SSN),
    STUDENT      INT      NOT NULL
        CONSTRAINT CHK_FILLS_STUDENT CHECK ( STUDENT BETWEEN 1 AND 32),
    CLASS_NUMBER INT      NOT NULL
        CONSTRAINT CHK_FILLS_CLASS_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12),
    CLASS_LETTER CHAR(1)  NOT NULL
        CONSTRAINT CHK_FILLS_CLASS_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    CONSTRAINT FK_FILLS_E_GRADEBOOK FOREIGN KEY (STUDENT, CLASS_NUMBER, CLASS_LETTER)
        REFERENCES E_GRADEBOOKS (STUDENT_NUMBER, CLASS_NUMBER, CLASS_LETTER),
    CONSTRAINT PK_FILLS PRIMARY KEY (TEACHER, STUDENT, CLASS_NUMBER, CLASS_LETTER)
);

CREATE TABLE GRADES
(
    VALUE        DECIMAL(3, 2) NOT NULL
        CONSTRAINT CHK_GRADES_VALUE CHECK ( VALUE BETWEEN 2.00 AND 6.00),
    TEACHER      CHAR(10)      NOT NULL
        CONSTRAINT FK_GRADES_TEACHER REFERENCES TEACHERS (SSN),
    SUBJECT      VARCHAR(16)   NOT NULL
        CONSTRAINT FK_GRADES_SUBJECT REFERENCES SUBJECTS (NAME),
    STUDENT      INT           NOT NULL
        CONSTRAINT CHK_GRADES_STUDENT CHECK ( STUDENT BETWEEN 1 AND 32),
    CLASS_NUMBER INT           NOT NULL
        CONSTRAINT CHK_GRADES_CLASS_NUMBER CHECK ( CLASS_NUMBER BETWEEN 8 AND 12 ),
    CLASS_LETTER CHAR(1)       NOT NULL
        CONSTRAINT CHK_GRADES_CLASS_LETTER CHECK ( CLASS_LETTER IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y' ,'z') ),
    CONSTRAINT FK_GRADES_E_GRADEBOOK FOREIGN KEY (STUDENT, CLASS_NUMBER, CLASS_LETTER)
        REFERENCES E_GRADEBOOKS (STUDENT_NUMBER, CLASS_NUMBER, CLASS_LETTER),
    CONSTRAINT PK_GRADES PRIMARY KEY (TEACHER, SUBJECT, STUDENT, CLASS_NUMBER, CLASS_LETTER)
);