--

set schema fn71845;

select *
    from TEACHES;

CREATE VIEW TEACHERS_SUBJECTS
AS
SELECT SSN, FIRST_NAME, THIRD_NAME AS LAST_NAME, SUBJECT, TELEPHONE_NUMBER
FROM TEACHERS T,
     TEACHES TE
WHERE T.SSN = TE.TEACHER;

SELECT *
FROM TEACHERS_SUBJECTS;


--Creating view of student in class 8

CREATE VIEW STUDENTS_8
AS
    SELECT *
    FROM STUDENTS
    WHERE CLASS_NUMBER = 8;